/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/app/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
  ],
  safelist: [
    'bg-white',
    'text-gray-900',
    'text-gray-700',
    'text-gray-800',
    'bg-gray-50',
    'text-blue-600',
    'underline',
    'font-bold',
    'font-semibold',
    'text-lg',
    'text-xl',
    'text-3xl',
    'text-4xl',
    'text-5xl',
    'mb-4',
    'mb-6',
    'px-6',
    'py-20',
    'pt-20',
    'min-h-screen',
    'flex',
    'items-center',
    'justify-center',
    'text-center',
    'max-w-3xl',
    'max-w-4xl',
    'max-w-6xl',
    'mx-auto',
    'space-y-4',
    'leading-relaxed',
    'fixed',
    'top-0',
    'w-full',
    'z-50',
    'transition-all',
    'duration-300',
    'bg-transparent',
    'backdrop-blur-md',
    'bg-white/70',
    'shadow-md',
    'justify-between',
    'space-x-6',
    'hidden',
    'md:flex',
    'md:hidden',
    'md:text-xl',
    'md:text-5xl',
    'hover:underline',
    'relative',
    'bottom-6',
    'right-6',
    'z-40',
    'p-3',
    'rounded-full',
    'bg-gray-800',
    'text-white',
    'hover:bg-gray-700',
    'shadow-lg',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}